[project]
name = "ile-ai"
version = "0.1.0"
description = "Is Life Expensive AI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.73.0",
    "pypdf2>=3.0.1",
    "typer>=0.15.2",
]
